# vim: set sw=4 ts=4 expandtab:
sudo: false
language: node_js

matrix:
    include:
        - node_js: "6"
        - node_js: "7"
install:
    - make get-deps
script:
    - make

notifications:
    email: false
