# vim: set sw=4 ts=4 expandtab:
sudo: false
language: node_js

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
matrix:
    include:
        - node_js: "6"
          env:
              - CXX=g++-4.8
        - node_js: "7"
          env:
              - CXX=g++-4.8
install:
    - make get-deps
script:
    - make

notifications:
    email: false
