# vim: set sw=4 ts=4 expandtab:
sudo: false
language: node_js

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
matrix:
    include:
        - node_js: "6"
          os: linux
          env:
              - CXX=g++-4.8
        - node_js: "6"
          os: osx
install:
    - .travis/install
script:
    - .travis/compile
    - .travis/package

notifications:
    email: false
