#!/usr/bin/env bash

set -e
set -u
set -o pipefail

APPLICATION_DIRECTORY="${APPLICATION_DIRECTORY:-src/Hangashore/}"
APPLICATION_NAME="${APPLICATION_NAME:-Hangashore}"
APPLICATION_OUTPUT_DIRECTORY="${APPLICATION_OUTPUT_DIRECTORY:-build/}"
CURRENT_PLATFORM="$(uname | awk '{print tolower($0)}')"
PLATFORM=${PLATFORM:-$CURRENT_PLATFORM}

npm install
npm run electron-packager -- "$APPLICATION_DIRECTORY" "$APPLICATION_NAME" \
	--out "$APPLICATION_OUTPUT_DIRECTORY" \
	--overwrite \
	--platform "$PLATFORM" \
	--app-category-type=public.app-category.reference
	--win32metadata.CompanyName="Lake Maps NL"
	--win32metadata.ProductName="${APPLICATION_NAME}"
	--asar
rm "${APPLICATION_OUTPUT_DIRECTORY%/}"/*/LICENSE
rm "${APPLICATION_OUTPUT_DIRECTORY%/}"/*/LICENSES.chromium.html
rm "${APPLICATION_OUTPUT_DIRECTORY%/}"/*/version

( cd "$APPLICATION_OUTPUT_DIRECTORY" && tar -czf "${APPLICATION_NAME}-${PLATFORM}${TRAVIS_TAG:+"-$TRAVIS_TAG"}.tgz" ./*/ )
( cd "$APPLICATION_OUTPUT_DIRECTORY" && zip -q9r "${APPLICATION_NAME}-${PLATFORM}${TRAVIS_TAG:+"-$TRAVIS_TAG"}.zip" ./*/ )
